### ISSUE TITLE
PNotify for React : Closing issue

### ISSUE THREAD

**Issue by satejrajam30** [zhuber/react-pnotify#1]
Hello, after the notification pops up, there is no close button & the notification does not go away. 

Can some one help with this? or a way to handle this. 

Thank you.

**Comment by zhuber** [comment]
Hey @satejrajam30 thanks for catching this issue. I've fixed it and you should be able to simply update react-pnotify to see that changes working.

Patched in PR#2: https://github.com/zhuber/react-pnotify/pull/2

**Comment by satejrajam30** [comment]
@zhuber great! Thanks mate!
